"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const adminController_js_1 = require("../controllers/adminController.js");
const yardController_js_1 = require("../controllers/yardController.js");
const preAdviceController_js_1 = require("../controllers/preAdviceController.js");
const inventoryController_js_1 = require("../controllers/inventoryController.js");
const billingRateController_js_1 = require("../controllers/billingRateController.js");
const bookingController_js_1 = require("../controllers/bookingController.js");
const authMiddleware_js_1 = require("../middleware/authMiddleware.js");
const paymentTypeController_js_1 = require("../controllers/paymentTypeController.js");
const uploadMiddleware_js_1 = require("../middleware/uploadMiddleware.js");
const asyncHandler_js_1 = __importDefault(require("../utils/asyncHandler.js"));
const router = express_1.default.Router();
router.use(authMiddleware_js_1.protect, authMiddleware_js_1.adminOnly);
router.get("/users", (0, authMiddleware_js_1.requirePermission)("userManagement", "view"), (0, asyncHandler_js_1.default)(adminController_js_1.listUsers));
router.get("/client-registrations", (0, authMiddleware_js_1.requirePermission)("clientVerification", "view"), (0, asyncHandler_js_1.default)(adminController_js_1.listClients));
router.get("/users/:id", (0, authMiddleware_js_1.requirePermission)("userManagement", "view"), (0, asyncHandler_js_1.default)(adminController_js_1.getUserById));
router.post("/users", (0, authMiddleware_js_1.requirePermission)("userManagement", "create"), (0, asyncHandler_js_1.default)(adminController_js_1.createAdminUser));
router.patch("/users/:id", (0, authMiddleware_js_1.requirePermission)("userManagement", "edit"), (0, asyncHandler_js_1.default)(adminController_js_1.updateUser));
router.delete("/users/:id", (0, authMiddleware_js_1.requirePermission)("userManagement", "delete"), (0, asyncHandler_js_1.default)(adminController_js_1.deleteUser));
router.patch("/clients/:id/approve", (0, authMiddleware_js_1.requirePermission)("clientVerification", "edit"), (0, asyncHandler_js_1.default)(adminController_js_1.approveClient));
router.patch("/clients/:id/reject", (0, authMiddleware_js_1.requirePermission)("clientVerification", "edit"), (0, asyncHandler_js_1.default)(adminController_js_1.rejectClient));
router.get("/bookings/summary", (0, authMiddleware_js_1.requirePermission)("bookings", "view"), (0, asyncHandler_js_1.default)(bookingController_js_1.getBookingSummary));
router.get("/bookings", (0, authMiddleware_js_1.requirePermission)("bookings", "view"), (0, asyncHandler_js_1.default)(bookingController_js_1.listAdminBookings));
router.get("/bookings/yard/blocks/:blockId/slots", (0, authMiddleware_js_1.requirePermission)("bookings", "view"), (0, asyncHandler_js_1.default)(bookingController_js_1.getYardBlockSlots));
router.get("/pre-advice-bookings", (0, authMiddleware_js_1.requirePermission)("preAdvice", "view"), (0, asyncHandler_js_1.default)(bookingController_js_1.listAdminBookings));
router.get("/pre-advice-bookings/yard/areas", (0, authMiddleware_js_1.requirePermission)("preAdvice", "view"), (0, asyncHandler_js_1.default)(yardController_js_1.listYardAreas));
router.get("/pre-advice-bookings/yard/blocks", (0, authMiddleware_js_1.requirePermission)("preAdvice", "view"), (0, asyncHandler_js_1.default)(yardController_js_1.listApprovalYardBlocks));
router.get("/pre-advice-bookings/yard/areas/:areaId/blocks", (0, authMiddleware_js_1.requirePermission)("preAdvice", "view"), (0, asyncHandler_js_1.default)(yardController_js_1.listYardBlocks));
router.get("/pre-advice-bookings/yard/blocks/:blockId/slots", (0, authMiddleware_js_1.requirePermission)("preAdvice", "view"), (0, asyncHandler_js_1.default)(bookingController_js_1.getYardBlockSlots));
router.patch("/pre-advice-bookings/:id/approve", (0, authMiddleware_js_1.requirePermission)("preAdvice", "edit"), (0, asyncHandler_js_1.default)(bookingController_js_1.approveBooking));
router.patch("/pre-advice-bookings/:id/reject", (0, authMiddleware_js_1.requirePermission)("preAdvice", "edit"), (0, asyncHandler_js_1.default)(bookingController_js_1.rejectBooking));
router.get("/bookings/:id", (0, authMiddleware_js_1.requirePermission)("bookings", "view"), (0, asyncHandler_js_1.default)(bookingController_js_1.getAdminBooking));
router.patch("/bookings/:id/approve", (0, authMiddleware_js_1.requirePermission)("bookings", "edit"), (0, asyncHandler_js_1.default)(bookingController_js_1.approveBooking));
router.patch("/bookings/:id/reject", (0, authMiddleware_js_1.requirePermission)("bookings", "edit"), (0, asyncHandler_js_1.default)(bookingController_js_1.rejectBooking));
router.patch("/bookings/:id/gate-in", (0, authMiddleware_js_1.requirePermission)("gateIn", "edit"), (0, asyncHandler_js_1.default)(bookingController_js_1.approveBookingGateIn));
router.patch("/bookings/:id/store", (0, authMiddleware_js_1.requirePermission)("inventory", "edit"), (0, asyncHandler_js_1.default)(bookingController_js_1.markBookingStored));
router.patch("/bookings/:id/billing-operation", (0, authMiddleware_js_1.requirePermission)("inventory", "edit"), (0, asyncHandler_js_1.default)(bookingController_js_1.updateBookingBillingOperation));
router.post("/bookings/:id/additional-charges", (0, authMiddleware_js_1.requirePermission)("paymentVerification", "edit"), (0, asyncHandler_js_1.default)(bookingController_js_1.addBookingAdditionalCharge));
router.delete("/bookings/:id/additional-charges/:chargeId", (0, authMiddleware_js_1.requirePermission)("paymentVerification", "edit"), (0, asyncHandler_js_1.default)(bookingController_js_1.deleteBookingAdditionalCharge));
router.patch("/bookings/:id/relocate", (0, authMiddleware_js_1.requirePermission)("inventory", "edit"), (0, asyncHandler_js_1.default)(bookingController_js_1.relocateBooking));
router.patch("/bookings/:id/payment/approve", (0, authMiddleware_js_1.requirePermission)("paymentVerification", "edit"), (0, asyncHandler_js_1.default)(bookingController_js_1.approveBookingPayment));
router.patch("/bookings/:id/payment/reject", (0, authMiddleware_js_1.requirePermission)("paymentVerification", "edit"), (0, asyncHandler_js_1.default)(bookingController_js_1.rejectBookingPayment));
router.patch("/bookings/:id/gate-out/approve", (0, authMiddleware_js_1.requirePermission)("gateOut", "edit"), (0, asyncHandler_js_1.default)(bookingController_js_1.approveBookingGateOut));
router.patch("/bookings/:id/gate-out/complete", (0, authMiddleware_js_1.requirePermission)("gateOut", "edit"), (0, asyncHandler_js_1.default)(bookingController_js_1.completeBookingGateOut));
router.get("/billing-rates", (0, authMiddleware_js_1.requirePermission)("rateSetup", "view"), (0, asyncHandler_js_1.default)(billingRateController_js_1.listBillingRates));
router.post("/billing-rates/reference-defaults", (0, authMiddleware_js_1.requirePermission)("rateSetup", "create"), (0, asyncHandler_js_1.default)(billingRateController_js_1.seedReferenceBillingRates));
router.post("/billing-rates", (0, authMiddleware_js_1.requirePermission)("rateSetup", "create"), (0, asyncHandler_js_1.default)(billingRateController_js_1.createBillingRate));
router.patch("/billing-rates/:id", (0, authMiddleware_js_1.requirePermission)("rateSetup", "edit"), (0, asyncHandler_js_1.default)(billingRateController_js_1.updateBillingRate));
router.delete("/billing-rates/:id", (0, authMiddleware_js_1.requirePermission)("rateSetup", "delete"), (0, asyncHandler_js_1.default)(billingRateController_js_1.deleteBillingRate));
router.get("/payment-types", (0, authMiddleware_js_1.requirePermission)("paymentTypes", "view"), (0, asyncHandler_js_1.default)(paymentTypeController_js_1.listPaymentTypes));
router.post("/payment-types", (0, authMiddleware_js_1.requirePermission)("paymentTypes", "create"), uploadMiddleware_js_1.paymentTypeUpload, (0, asyncHandler_js_1.default)(paymentTypeController_js_1.createPaymentType));
router.patch("/payment-types/:id", (0, authMiddleware_js_1.requirePermission)("paymentTypes", "edit"), uploadMiddleware_js_1.paymentTypeUpload, (0, asyncHandler_js_1.default)(paymentTypeController_js_1.updatePaymentType));
router.delete("/payment-types/:id", (0, authMiddleware_js_1.requirePermission)("paymentTypes", "delete"), (0, asyncHandler_js_1.default)(paymentTypeController_js_1.deletePaymentType));
router.get("/pre-advices/yard/areas", (0, authMiddleware_js_1.requirePermission)("preAdvice", "view"), (0, asyncHandler_js_1.default)(yardController_js_1.listYardAreas));
router.get("/pre-advices/yard/blocks", (0, authMiddleware_js_1.requirePermission)("preAdvice", "view"), (0, asyncHandler_js_1.default)(yardController_js_1.listApprovalYardBlocks));
router.get("/pre-advices/yard/areas/:areaId/blocks", (0, authMiddleware_js_1.requirePermission)("preAdvice", "view"), (0, asyncHandler_js_1.default)(yardController_js_1.listYardBlocks));
router.get("/pre-advices/yard/blocks/:blockId/slots", (0, authMiddleware_js_1.requirePermission)("preAdvice", "view"), (0, asyncHandler_js_1.default)(bookingController_js_1.getYardBlockSlots));
router.get("/pre-advices", (0, authMiddleware_js_1.requirePermission)("preAdvice", "view"), (0, asyncHandler_js_1.default)(preAdviceController_js_1.listAdminPreAdvices));
router.patch("/pre-advices/:id/confirm", (0, authMiddleware_js_1.requirePermission)("preAdvice", "edit"), (0, asyncHandler_js_1.default)(preAdviceController_js_1.confirmPreAdvice));
router.patch("/pre-advices/:id/reject", (0, authMiddleware_js_1.requirePermission)("preAdvice", "edit"), (0, asyncHandler_js_1.default)(preAdviceController_js_1.rejectPreAdvice));
router.get("/gate-in/ready", (0, authMiddleware_js_1.requirePermission)("gateIn", "view"), (0, asyncHandler_js_1.default)(preAdviceController_js_1.listGateInReadyPreAdvices));
router.post("/gate-in/:preAdviceId/complete", (0, authMiddleware_js_1.requirePermission)("gateIn", "create"), (0, asyncHandler_js_1.default)(preAdviceController_js_1.completeGateIn));
router.get("/yard/summary", (0, authMiddleware_js_1.requirePermission)("yardSetup", "view"), (0, asyncHandler_js_1.default)(yardController_js_1.getYardSummary));
router.get("/yard/areas", (0, authMiddleware_js_1.requirePermission)("yardSetup", "view"), (0, asyncHandler_js_1.default)(yardController_js_1.listYardAreas));
router.post("/yard/areas", (0, authMiddleware_js_1.requirePermission)("yardSetup", "create"), (0, asyncHandler_js_1.default)(yardController_js_1.createYardArea));
router.patch("/yard/areas/:id", (0, authMiddleware_js_1.requirePermission)("yardSetup", "edit"), (0, asyncHandler_js_1.default)(yardController_js_1.updateYardArea));
router.delete("/yard/areas/:id", (0, authMiddleware_js_1.requirePermission)("yardSetup", "delete"), (0, asyncHandler_js_1.default)(yardController_js_1.deleteYardArea));
router.get("/yard/areas/:areaId/blocks", (0, authMiddleware_js_1.requirePermission)("inventory", "view"), (0, asyncHandler_js_1.default)(yardController_js_1.listYardBlocks));
router.post("/yard/areas/:areaId/blocks", (0, authMiddleware_js_1.requirePermission)("inventory", "create"), (0, asyncHandler_js_1.default)(yardController_js_1.createYardBlock));
router.patch("/yard/blocks/:id", (0, authMiddleware_js_1.requirePermission)("inventory", "edit"), (0, asyncHandler_js_1.default)(yardController_js_1.updateYardBlock));
router.delete("/yard/blocks/:id", (0, authMiddleware_js_1.requirePermission)("inventory", "delete"), (0, asyncHandler_js_1.default)(yardController_js_1.deleteYardBlock));
router.get("/inventory/containers", (0, authMiddleware_js_1.requirePermission)("inventory", "view"), (0, asyncHandler_js_1.default)(inventoryController_js_1.listInventoryContainers));
router.patch("/inventory/containers/:id/assign", (0, authMiddleware_js_1.requirePermission)("inventory", "edit"), (0, asyncHandler_js_1.default)(inventoryController_js_1.assignInventoryContainer));
router.get("/inventory/summary", (0, authMiddleware_js_1.requirePermission)("inventory", "view"), (0, asyncHandler_js_1.default)(yardController_js_1.getYardSummary));
router.get("/inventory/areas", (0, authMiddleware_js_1.requirePermission)("inventory", "view"), (0, asyncHandler_js_1.default)(yardController_js_1.listYardAreas));
router.get("/inventory/areas/:areaId/blocks", (0, authMiddleware_js_1.requirePermission)("inventory", "view"), (0, asyncHandler_js_1.default)(yardController_js_1.listYardBlocks));
router.get("/inventory/blocks/:blockId/slots", (0, authMiddleware_js_1.requirePermission)("inventory", "view"), (0, asyncHandler_js_1.default)(bookingController_js_1.getYardBlockSlots));
router.post("/inventory/areas/:areaId/blocks", (0, authMiddleware_js_1.requirePermission)("inventory", "create"), (0, asyncHandler_js_1.default)(yardController_js_1.createYardBlock));
router.patch("/inventory/blocks/:id", (0, authMiddleware_js_1.requirePermission)("inventory", "edit"), (0, asyncHandler_js_1.default)(yardController_js_1.updateYardBlock));
router.delete("/inventory/blocks/:id", (0, authMiddleware_js_1.requirePermission)("inventory", "delete"), (0, asyncHandler_js_1.default)(yardController_js_1.deleteYardBlock));
exports.default = router;
